apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: campuspulse-ingress
  namespace: campuspulse
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: campuspulse
  policyTypes: ["Ingress"]
  ingress:
    - from:
        - namespaceSelector: {}
      ports:
        - protocol: TCP
          port: 8000

