apiVersion: v1
kind: Service
metadata:
  name: campuspulse
  namespace: campuspulse
  labels:
    app.kubernetes.io/name: campuspulse
spec:
  selector:
    app.kubernetes.io/name: campuspulse
  ports:
    - name: http
      port: 80
      targetPort: http

